### ISSUE TITLE
UX on landing page

### ISSUE THREAD

**Issue by lostdesign** [bartlomein/World-Cup-2018#2]
![bildschirmfoto 2018-06-29 um 16 23 54](https://user-images.githubusercontent.com/5164617/42097629-e16351f0-7bb8-11e8-9f2c-d8d3eaf5a214.png)

As of now, it's difficult to know where the user should click in order to get to the other pages. The links could need some more emphasis.

- different weight in typo, color or styling could help
- including them in the "hero" as call to action
- the "hero" could be centered completely, to give both boxes more space to breath

_As mentioned may be opening a pr tonight, just creating this to remember it later ^^_

**Comment by bartlomein** [comment]
Ya I had some trouble setting up a decent menu. Def have to still work on it. If you end up working on it, def let me know what you come up with!

**Comment by bartlomein** [comment]
fixed with latest push
