### ISSUE TITLE
Menu blocking content

### ISSUE THREAD

**Issue by lostdesign** [bartlomein/World-Cup-2018#3]
![bildschirmfoto 2018-06-29 um 16 27 28](https://user-images.githubusercontent.com/5164617/42097810-5f14386c-7bb9-11e8-82ea-bde82d47700c.png)

Another minor thing, the menu is blocking the content, could be resolved together with #2. On the `knockout` page the content is shown below the menu, might be an option. 

Yet the whitespace above the content might not look as good then. Same thing, gonna try to improve later ^^

**Comment by bartlomein** [comment]
fixed in latest push
